import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Sidebar from "./sidebar";


const poppins = Poppins({
  weight: ['400', '700'], // Specify the desired font weights
  subsets: ['latin'], // Specify the desired subsets
});

export const metadata: Metadata = {
  title: "Best App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Header/>
      <Sidebar/>
        {children}</body>
    </html>
  );
}
